apiVersion: v1
kind: Pod
metadata:
  name: ibankingsafepod
spec:
  containers:
    - name: ibankingsafecontainer
      image: mgmbcssantosh86/ibankingsafe:1.0
      resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
      ports:
        - name: tomcatport
          containerPort: 8082
          protocol: TCP
      readinessProbe:
        httpGet:
          path: /actuator/health/readiness
          port: 8082
        initialDelaySeconds: 15
        timeoutSeconds: 15
        failureThreshold: 3
      livenessProbe:
        httpGet:
          path: /actuator/health/liveness
          port: 8082
        initialDelaySeconds: 15
        timeoutSeconds: 15
        failureThreshold: 3
      env:
        - name: "db.username"
          valueFrom:
            secretKeyRef:
              name: ibankingsafesecret
              key: password